M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2025-05-23T21:37:58-0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-23T21:37:58-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.2472Y-2.9758
X5.2472Y-3.1667
T2
X5.128Y-2.964
X5.128Y-3.1785
M30
