M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Wed 10 Jul 2024 21:13:57 -03
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-10T21:13:57-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.2472Y-2.9758
X5.2472Y-3.1667
T2
X5.128Y-2.964
X5.128Y-3.1785
M30
